


# VARIABLES ARE THE PLACEHOLDER WHERE WE CAN STORE VALUES / DATA



# VARIABLE DATA TYPES?

# DIFFERENT DATA TYPES ARE?

# VARIABLE DECLARATION

# VARIABLE RE DECLARATION

# VARIABLE IS CREATED THE MOMENT YOU FIRST ASSIGN A VALUE TO IT
